### ISSUE TITLE
Division query

### ISSUE THREAD

**Issue by christinesam** [Shih-ChunHuang/Frontend-webService#3]
"Pick one query of this category and provide an interface for the user to choose this query."

Choose movie that is rated 5 stars by all users

**select m.title, m.releasedate from movie m 
where not exists((select u1.accountname from users u1) 
minus (select u2.accountname from users u2, review r 
where r.rating = 5 and u2.accountname = r.accountname and r.title = m.title and r.releasedate = m.releasedate));**

**Comment by blindacai** [comment]
I directly used the above query in our code

**Comment by christinesam** [comment]
FINISHED! WORKS!
