### ISSUE TITLE
Join query

### ISSUE THREAD

**Issue by christinesam** [Shih-ChunHuang/Frontend-webService#6]
"pick one query of this category and provide an interface for the user to choose this query."

The page for a specific movie joins information from movies, actors, reviews, and comments table.
- Now that I think about it, it doesnt make sense to join all those tables. reviews, comments, and actors having nothing in common to join in.

joining movies and actors

**select m.title, m.releasedate, m.director, m.distributedcompany, 
a.name, a.birthday
from movie m left outer join acts_in a on (m.releasedate = a.releasedate and m.title = a.title)**

**Comment by blindacai** [comment]
Based on the current UI, we are only joining movie and comments table

**Comment by christinesam** [comment]
Linda, could you also do a join for the reviews onto the single movie page? since we will be inserting reviews, so we should be able to see reviews as well

**Comment by christinesam** [comment]
FINISHED!
